version: "3.8"
services:
  router:
    env_file:
      - .env
    image: traefik:v3.0
    container_name: "router"
    ports:
      - "80:80"
      - "8080"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/letsencrypt:/letsencrypt"
      - "/var/log/eb-docker/containers/router:/log"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`router.i-code.xyz`, `www.router.i-code.xyz`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=router:${BASIC_AUTH_PASSWORD}"

  api:
    build:
      context: ./directus
      dockerfile: Dockerfile
    image: directus/directus:10.11.0
    env_file:
      - .env
    container_name: api
    restart: on-failure
    ports:
      - "8055:8055"
    environment:
      PORT: 8055
      PUBLIC_URL: "http://api.i-code.xyz/"
      DB_SSL: "true"
      RATE_LIMITER_ENABLED: "false"
      RATE_LIMITER_STORE: "memory"
      RATE_LIMITER_POINTS: 25
      RATE_LIMITER_DURATION: 1
      CACHE_ENABLED: "false"
      CACHE_AUTO_PURGE: "true"
      CACHE_AUTO_PURGE_IGNORE_LIST: "directus_activity,directus_presets"
      CACHE_STORE: "memory"
      ASSETS_CACHE_TTL: "1d"
      STORAGE_LOCATIONS: "Cloudinary"
      STORAGE_CLOUDINARY_DRIVER: "cloudinary"
      ACCESS_TOKEN_TTL: "15m"
      SESSION_COOKIE_NAME: "directus_session_token"
      SESSION_COOKIE_SAME_SITE: "lax"
      SESSION_COOKIE_SECURE: "false"
      SESSION_COOKIE_TTL: "1d"
      REFRESH_TOKEN_TTL: "7d"
      REFRESH_TOKEN_COOKIE_SECURE: "false"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      REFRESH_TOKEN_COOKIE_NAME: "directus_refresh_token"
      CORS_ENABLED: "true"
      KEY: "${KEY_DIRECTUS}"
      SECRET: "${SECRET_DIRECTUS}"
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET,POST,PATCH,DELETE"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      CORS_EXPOSED_HEADERS: "Content-Range"
      CORS_CREDENTIALS: "true"
      CORS_MAX_AGE: 18000
      EXTENSIONS_PATH: "./extensions"
      EXTENSIONS_AUTO_RELOAD: "false"
      EMAIL_ALLOW_GUEST_SEND: "false"
      EMAIL_VERIFY_SETUP: "true"
      TELEMETRY: "false"
      GRAPHQL_INTROSPECTION: "true"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "http://api.i-code.xyz/, http://api.i-code.xyz/"
    depends_on:
      - router
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.i-code.xyz`, `www.api.i-code.xyz`)" # Hosts définis
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8055"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    name: traefik-net