# traefik.yml
api:
  dashboard: true

log:
  level: DEBUG
  filePath: /log/traefik.log

accessLog:
  filePath: /log/access.json
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"

core:
  defaultRuleSyntax: v2