api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

log:
  level: DEBUG
  filePath: "/log/traefik.log"
  format: common

accessLog:
  filePath: "/log/access.json"
  format: json

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: "traefik-net"
    exposedByDefault: false

serversTransport:
  insecureSkipVerify: true

core:
  defaultRuleSyntax: v2