api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

log:
  level: DEBUG
  filePath: "/log/traefik.log"
  format: common

accessLog:
  filePath: "/log/access.json"
  format: json

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: "traefik-net"
    exposedByDefault: false

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: m.loulou9311@gmail.com
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web