/* eslint-disable */
/* prettier-ignore */

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  query: 'Query';
  mutation: never;
  subscription: 'Subscription';
  types: {
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'Home': { name: 'Home'; type: { kind: 'OBJECT'; name: 'Home'; ofType: null; } }; 'Home_by_version': { name: 'Home_by_version'; type: { kind: 'OBJECT'; name: 'version_Home'; ofType: null; } }; }; };
    'Home': { kind: 'OBJECT'; name: 'Home'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'date_created': { name: 'date_created'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'date_created_func': { name: 'date_created_func'; type: { kind: 'OBJECT'; name: 'datetime_functions'; ofType: null; } }; 'date_updated': { name: 'date_updated'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'date_updated_func': { name: 'date_updated_func'; type: { kind: 'OBJECT'; name: 'datetime_functions'; ofType: null; } }; 'Hero_description': { name: 'Hero_description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Hero_title': { name: 'Hero_title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Portrait': { name: 'Portrait'; type: { kind: 'OBJECT'; name: 'directus_files'; ofType: null; } }; 'Hero_a_propos_texte': { name: 'Hero_a_propos_texte'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Hero_a_propos_titre': { name: 'Hero_a_propos_titre'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Hero_a_propos_sous_titre': { name: 'Hero_a_propos_sous_titre'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'ID': unknown;
    'String': unknown;
    'Date': unknown;
    'datetime_functions': { kind: 'OBJECT'; name: 'datetime_functions'; fields: { 'year': { name: 'year'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'month': { name: 'month'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'week': { name: 'week'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'day': { name: 'day'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'weekday': { name: 'weekday'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'hour': { name: 'hour'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'minute': { name: 'minute'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'second': { name: 'second'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Int': unknown;
    'directus_files': { kind: 'OBJECT'; name: 'directus_files'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'filename_disk': { name: 'filename_disk'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'filename_download': { name: 'filename_download'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'charset': { name: 'charset'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'filesize': { name: 'filesize'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; } }; 'width': { name: 'width'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'height': { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'duration': { name: 'duration'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'embed': { name: 'embed'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'location': { name: 'location'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'tags': { name: 'tags'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'tags_func': { name: 'tags_func'; type: { kind: 'OBJECT'; name: 'count_functions'; ofType: null; } }; 'metadata': { name: 'metadata'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'metadata_func': { name: 'metadata_func'; type: { kind: 'OBJECT'; name: 'count_functions'; ofType: null; } }; 'focal_point_x': { name: 'focal_point_x'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'focal_point_y': { name: 'focal_point_y'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'GraphQLBigInt': unknown;
    'JSON': unknown;
    'count_functions': { kind: 'OBJECT'; name: 'count_functions'; fields: { 'count': { name: 'count'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'directus_files_filter': { kind: 'INPUT_OBJECT'; name: 'directus_files_filter'; inputFields: [{ name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'filename_disk'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'filename_download'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'title'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'charset'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'filesize'; type: { kind: 'INPUT_OBJECT'; name: 'big_int_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'width'; type: { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'height'; type: { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'duration'; type: { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'embed'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'description'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'location'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'tags'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'tags_func'; type: { kind: 'INPUT_OBJECT'; name: 'count_function_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'metadata'; type: { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'metadata_func'; type: { kind: 'INPUT_OBJECT'; name: 'count_function_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'focal_point_x'; type: { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; ofType: null; }; defaultValue: null }, { name: 'focal_point_y'; type: { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; ofType: null; }; defaultValue: null }, { name: '_and'; type: { kind: 'LIST'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'directus_files_filter'; ofType: null; }; }; defaultValue: null }, { name: '_or'; type: { kind: 'LIST'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'directus_files_filter'; ofType: null; }; }; defaultValue: null }]; };
    'string_filter_operators': { kind: 'INPUT_OBJECT'; name: 'string_filter_operators'; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_contains'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_icontains'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_ncontains'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_starts_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nstarts_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_istarts_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nistarts_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_ends_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nends_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_iends_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_niends_with'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: '_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_nnull'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_empty'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_nempty'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'Boolean': unknown;
    'big_int_filter_operators': { kind: 'INPUT_OBJECT'; name: 'big_int_filter_operators'; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; defaultValue: null }, { name: '_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_nnull'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_between'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; }; defaultValue: null }, { name: '_nbetween'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLBigInt'; ofType: null; }; }; defaultValue: null }]; };
    'number_filter_operators': { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; defaultValue: null }, { name: '_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_nnull'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_between'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; }; defaultValue: null }, { name: '_nbetween'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'GraphQLStringOrFloat'; ofType: null; }; }; defaultValue: null }]; };
    'GraphQLStringOrFloat': unknown;
    'count_function_filter_operators': { kind: 'INPUT_OBJECT'; name: 'count_function_filter_operators'; inputFields: [{ name: 'count'; type: { kind: 'INPUT_OBJECT'; name: 'number_filter_operators'; ofType: null; }; defaultValue: null }]; };
    'version_Home': { kind: 'OBJECT'; name: 'version_Home'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'date_created': { name: 'date_created'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'date_created_func': { name: 'date_created_func'; type: { kind: 'OBJECT'; name: 'datetime_functions'; ofType: null; } }; 'date_updated': { name: 'date_updated'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'date_updated_func': { name: 'date_updated_func'; type: { kind: 'OBJECT'; name: 'datetime_functions'; ofType: null; } }; 'Hero_description': { name: 'Hero_description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Hero_title': { name: 'Hero_title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Portrait': { name: 'Portrait'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'Hero_a_propos_texte': { name: 'Hero_a_propos_texte'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Hero_a_propos_titre': { name: 'Hero_a_propos_titre'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'Hero_a_propos_sous_titre': { name: 'Hero_a_propos_sous_titre'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'directus_files_mutated': { name: 'directus_files_mutated'; type: { kind: 'OBJECT'; name: 'directus_files_mutated'; ofType: null; } }; 'Home_mutated': { name: 'Home_mutated'; type: { kind: 'OBJECT'; name: 'Home_mutated'; ofType: null; } }; }; };
    'directus_files_mutated': { kind: 'OBJECT'; name: 'directus_files_mutated'; fields: { 'key': { name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'event': { name: 'event'; type: { kind: 'ENUM'; name: 'EventEnum'; ofType: null; } }; 'data': { name: 'data'; type: { kind: 'OBJECT'; name: 'directus_files'; ofType: null; } }; }; };
    'EventEnum': { kind: 'ENUM'; name: 'EventEnum'; type: 'create' | 'update' | 'delete'; };
    'Home_mutated': { kind: 'OBJECT'; name: 'Home_mutated'; fields: { 'key': { name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'event': { name: 'event'; type: { kind: 'ENUM'; name: 'EventEnum'; ofType: null; } }; 'data': { name: 'data'; type: { kind: 'OBJECT'; name: 'Home'; ofType: null; } }; }; };
  };
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}